-- ============================================================
-- AIMD Backend — Supabase Postgres Migrations
-- ============================================================
-- Run this SQL in the Supabase Dashboard → SQL Editor, or via
-- the Supabase CLI (`supabase db push`).
--
-- These tables use UUIDs as primary keys (matching the job_id
-- format generated by the Python backend) and TIMESTAMPTZ for
-- all timestamp columns.
-- ============================================================

-- Enable the pgcrypto extension for gen_random_uuid() if not already enabled.
CREATE EXTENSION IF NOT EXISTS pgcrypto;


-- -----------------------------------------------------------
-- 1. cases — Police case / FIR tracking
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS cases (
    case_id     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    officer_id  TEXT NOT NULL,
    title       TEXT NOT NULL DEFAULT '',
    status      TEXT NOT NULL DEFAULT 'open',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE cases IS 'Police case / FIR records linked to evidence analysis jobs.';


-- -----------------------------------------------------------
-- 2. media_jobs — Image/Video deepfake analysis jobs
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS media_jobs (
    job_id                UUID PRIMARY KEY,
    case_id               UUID REFERENCES cases(case_id) ON DELETE SET NULL,
    original_filename     TEXT,
    file_url              TEXT,
    sha256_hash           TEXT,
    file_type             TEXT,                -- 'image' or 'video'
    status                TEXT NOT NULL DEFAULT 'queued',
    classification_result JSONB DEFAULT '{}'::jsonb,
    confidence_score      DOUBLE PRECISION,
    metadata_info         JSONB DEFAULT '{}'::jsonb,
    model_version         TEXT,
    frames_analyzed       INTEGER,
    fallback_active       BOOLEAN DEFAULT FALSE,
    error                 TEXT,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at          TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_media_jobs_case_id ON media_jobs(case_id);
CREATE INDEX IF NOT EXISTS idx_media_jobs_status ON media_jobs(status);

COMMENT ON TABLE media_jobs IS 'Image/video deepfake analysis jobs with full forensic results stored as JSONB.';


-- -----------------------------------------------------------
-- 3. audio_jobs — Audio synthetic-voice analysis jobs
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS audio_jobs (
    job_id                UUID PRIMARY KEY,
    case_id               UUID REFERENCES cases(case_id) ON DELETE SET NULL,
    original_filename     TEXT,
    file_url              TEXT,
    sha256_hash           TEXT,
    status                TEXT NOT NULL DEFAULT 'queued',
    classification_result JSONB DEFAULT '{}'::jsonb,
    synthetic_voice_score DOUBLE PRECISION,
    duration_seconds      DOUBLE PRECISION,
    sample_rate_hz        INTEGER,
    segments_analyzed     INTEGER,
    model_version         TEXT,
    mel_spectrogram_url   TEXT,
    fallback_active       BOOLEAN DEFAULT FALSE,
    error                 TEXT,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at          TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_audio_jobs_case_id ON audio_jobs(case_id);
CREATE INDEX IF NOT EXISTS idx_audio_jobs_status ON audio_jobs(status);

COMMENT ON TABLE audio_jobs IS 'Audio deepfake / synthetic voice analysis jobs.';


-- -----------------------------------------------------------
-- 4. phishing_logs — Domain reputation cache for Chrome Extension
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS phishing_logs (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    domain      TEXT NOT NULL,
    status      TEXT NOT NULL DEFAULT 'SAFE',    -- SAFE | SUSPICIOUS | MALICIOUS
    report_data JSONB DEFAULT '{}'::jsonb,
    checked_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_phishing_logs_domain ON phishing_logs(domain);
CREATE INDEX IF NOT EXISTS idx_phishing_logs_checked_at ON phishing_logs(checked_at);

COMMENT ON TABLE phishing_logs IS 'Cached domain reputation results from VirusTotal / Safe Browsing for the Chrome Extension check-domain endpoint.';


-- -----------------------------------------------------------
-- Storage Bucket (create via Supabase Dashboard)
-- -----------------------------------------------------------
-- Bucket name: evidence-files
-- Public: No (use signed URLs or service-role access only)
-- Allowed MIME types: image/*, video/*, audio/*, application/octet-stream
-- Max file size: 100MB (match MAX_UPLOAD_SIZE_MB)
--
-- The bucket must be created manually in the Supabase Dashboard:
--   Storage → New Bucket → "evidence-files" → Private
